# Generated by Django 5.0.1 on 2024-02-01 10:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newsbd",
            options={"verbose_name": "Новость", "verbose_name_plural": "Новости"},
        ),
    ]
