# Generated by Django 5.0.1 on 2024-02-07 11:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_alter_newsbd_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newsbd",
            options={
                "permissions": [
                    ("qwerty", "Возможность qwerty"),
                    ("can_smth", "Возможность can_smth"),
                ],
                "verbose_name": "Новость",
                "verbose_name_plural": "Новости",
            },
        ),
    ]
