# Generated by Django 5.0.4 on 2024-04-10 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(blank=True, null=True, verbose_name="Текст")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="image/%Y/%m/%d",
                        verbose_name="Фотография",
                    ),
                ),
                (
                    "datetime",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Дата и время"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        blank=True, default=False, null=True, verbose_name="Удалено"
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Отправитель",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Название")),
                (
                    "invite_code",
                    models.CharField(
                        blank=True,
                        default="3BA8ZPKQ967JOS67W2AO",
                        max_length=20,
                        null=True,
                        verbose_name="Код приглашения",
                    ),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        to=settings.AUTH_USER_MODEL, verbose_name="Участники"
                    ),
                ),
                (
                    "messages",
                    models.ManyToManyField(to="chat.message", verbose_name="Сообщения"),
                ),
            ],
        ),
    ]
