# Generated by Django 5.0.4 on 2024-04-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_alter_room_invite_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="image",
        ),
        migrations.AlterField(
            model_name="room",
            name="invite_code",
            field=models.CharField(
                blank=True,
                default="MQNULM962PD24ZE679ZW",
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Код приглашения",
            ),
        ),
    ]
