# Generated by Django 5.0.4 on 2024-04-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_remove_message_image_alter_room_invite_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="text",
            field=models.TextField(default="asda", verbose_name="Текст"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="room",
            name="invite_code",
            field=models.CharField(
                blank=True,
                default="5Y15K25V3Y0SF6XFE9J0",
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Код приглашения",
            ),
        ),
    ]
