# Generated by Django 5.0.4 on 2024-04-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_alter_message_text_alter_room_invite_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ("datetime",)},
        ),
        migrations.AlterField(
            model_name="room",
            name="invite_code",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="Код приглашения",
            ),
        ),
    ]
