# Generated by Django 5.0.1 on 2024-02-28 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("magazine", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date_finish",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата завершения заказа"
            ),
        ),
        migrations.AlterField(
            model_name="pos_order",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="magazine.order",
                verbose_name="Заказ",
            ),
        ),
    ]
