# Generated by Django 5.0.4 on 2024-05-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("green_shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="green",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="image/%Y/%m/%d",
                verbose_name="Фотография",
            ),
        ),
    ]
